### ISSUE TITLE
ModuleNotFoundError: No module named 'DOTA_devkit_YOLO'

### ISSUE THREAD

**Issue by Best-effort** [buzhidaoshenme/YOLOX-OBB#9]
如题。
您好，我在运行您的代码的时候发现会提示如下错误：
Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from yolox.core import Trainer, launch
  File "/usr/local/anaconda3/lib/python3.8/site-packages/yolox-0.1.0-py3.8-linux-x86_64.egg/yolox/__init__.py", line 4, in <module>
    from .utils import configure_module
  File "/usr/local/anaconda3/lib/python3.8/site-packages/yolox-0.1.0-py3.8-linux-x86_64.egg/yolox/utils/__init__.py", line 6, in <module>
    from .boxes import *
  File "/usr/local/anaconda3/lib/python3.8/site-packages/yolox-0.1.0-py3.8-linux-x86_64.egg/yolox/utils/boxes.py", line 7, in <module>
    from DOTA_devkit_YOLO import polyiou
ModuleNotFoundError: No module named 'DOTA_devkit_YOLO'

我去yolox/utils/boxes.py中查看发现了from DOTA_devkit_YOLO import polyiou，尝试把from导入模块改成相对路径，依旧会出现这个问题？ 麻烦您帮忙解答一下，万分感谢！！

**Comment by buzhidaoshenme** [comment]
你按照这个步骤安装过了吗
![image](https://user-images.githubusercontent.com/23292900/164715087-04ce0bb4-ed4f-4995-83a5-56b3928e1969.png)
如果安装过了，你试一下在DOTA_devkit_YOLO下新建一个__init__.py文件, 然后再导入试试；
如果还不行，你参考下[ResultMerge.py](https://github.com/CAPTAIN-WHU/DOTA_devkit/blob/master/ResultMerge.py), 这个里面也使用了import  polyiou
